version: '3.8'

services:
  app:
    build: .
    container_name: index-tracker-app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - DATABASE_PATH=/app/data/stocks.db
      - EXPORT_DIR=/app/exports
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports
    depends_on:
      - redis
    networks:
      - index-tracker-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: index-tracker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - index-tracker-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis-data:

networks:
  index-tracker-network:
    driver: bridge